const menuData=[
{title:'Coffee',label:'กาแฟ',group:'coffee',items:[['Espresso Shot','เอสเพรสโซ่ ช็อต','ร้อน 60'],['Americano','อเมริกาโน่','ร้อน 60 · เย็น 65'],['Thai Espresso','เอสเพรสโซ่เย็น','เย็น 75'],['Latte','ลาเต้','ร้อน 75 · เย็น 75'],['Cappuccino','คาปูชิโน่','ร้อน 75 · เย็น 75'],['Mocha','ม็อคค่า','เย็น 80'],['Caramel Latte','คาราเมลลาเต้','เย็น 90'],['Caramel Macchiato','คาราเมลมัคคิอาโต้','เย็น 105']]},
{title:'Mixed Black Coffee',label:'กาแฟดำผสม',group:'coffee',items:[['Coconut Black','กาแฟมะพร้าว','เย็น 80'],['Orange Black','กาแฟส้ม','เย็น 80'],['Mango Black','กาแฟมะม่วง','เย็น 80'],['Matcha Black','กาแฟมัทฉะ','เย็น 80'],['Caramel Black','กาแฟคาราเมล','เย็น 80'],['Honey Black','กาแฟน้ำผึ้ง','เย็น 80'],['Orange Soda Black','กาแฟส้มโซดา','เย็น 85']]},
{title:'Matcha',label:'มัทฉะ',group:'matcha',items:[['Pure Matcha','เพียวมัทฉะ (Mineral water)','Premium 70 · Ceremonial 90'],['Matcha Latte','มัทฉะลาเต้','Premium 75 · Ceremonial 95'],['Honey Matcha','มัทฉะน้ำผึ้ง','Premium 75 · Ceremonial 95'],['Yuzu Lemon Matcha','มัทฉะน้ำผึ้งยูซุ','Premium 80 · Ceremonial 100'],['Honey Lemon Matcha','มัทฉะน้ำผึ้งมะนาว','Premium 80 · Ceremonial 100'],['Lychee Matcha','มัทฉะลิ้นจี่','Premium 80 · Ceremonial 100'],['Strawberry Matcha Latte','มัทฉะสตรอว์เบอร์รี่','Premium 90 · Ceremonial 120'],['Orange Matcha','มัทฉะส้ม','Premium 90 · Ceremonial 120'],['Coconut Matcha','มัทฉะมะพร้าว (No Milk)','Premium 90 · Ceremonial 120'],['Matcha Latte Coffee','มัทฉะลาเต้คอฟฟี่','Premium 90 · Ceremonial 120']]},
{title:'Tea',label:'ชา',group:'tea',items:[['Thai Milk Tea','ชาไทย','เย็น 60 / 65'],['Green Milk Tea','ชาเขียว','เย็น 60 / 65'],['Pure Green Tea','ชาเขียว (ไม่ใส่นม)','เย็น 50 / 55'],['Peach Tea','ชาพีช','เย็น 60'],['Lemon Tea','ชามะนาว','เย็น 60'],['Green Lemon Tea','ชาเขียวมะนาว','เย็น 60']]},
{title:'Cocoa',label:'โกโก้',group:'other',items:[['Cocoa','โกโก้','ร้อน 60 · เย็น 75'],['Thai Tea - Cocoa','โกโก้ชาไทย','เย็น 75'],['Green Tea - Cocoa','โกโก้ชาเขียว','เย็น 75'],['Pink - Cocoa','โกโก้นมชมพู','เย็น 75'],['Mint - Cocoa','โกโก้มิ้นท์','เย็น 75'],['Caramel - Cocoa','โกโก้คาราเมล','เย็น 75'],['Orange - Cocoa','โกโก้ส้ม','เย็น 75'],['Mango - Cocoa','โกโก้มะม่วง','เย็น 75']]},
{title:'Milk',label:'นม',group:'other',items:[['Fresh Milk','นมสด','ร้อน 50 · เย็น 60'],['Pink Milk','นมชมพู','เย็น 65'],['Vanilla Milk','นมวานิลลา','เย็น 65'],['Caramel Milk','นมคาราเมล','เย็น 65'],['Mint Milk','นมมิ้นท์','เย็น 70'],['Strawberry Milk','นมสตรอว์เบอร์รี่','เย็น 70']]},
{title:'Italian Soda',label:'อิตาเลียนโซดา',group:'other',items:[['Blue Carucao Soda','บลูฮาวาย','เย็น 65'],['Kiwi','กีวี','เย็น 65'],['Lychee','ลิ้นจี่','เย็น 65'],['Strawberry','สตรอว์เบอร์รี่','เย็น 65'],['Peach','พีช','เย็น 65'],['Yuzu','ยูซุ','เย็น 65'],['Honey Yuzu','ยูซุน้ำผึ้ง','เย็น 75'],['Strawberry Yuzu','ยูซุสตรอว์เบอร์รี่','เย็น 75']]},
{title:'Coconut',label:'น้ำมะพร้าว',group:'other',items:[['Coconut Milk Shake','น้ำมะพร้าวปั่นนมสด','เย็น 80'],['Coconut Frappe','น้ำมะพร้าวปั่น (No milk)','เย็น 75']]},
{title:'Croffle',label:'รออบ 10–15 นาที',group:'food',items:[['Plain Croffle','ไม่มีน้ำตาล','65'],['Sugar Caramel','เคลือบน้ำตาลคาราเมล','70'],['Dark Chocolate Croffle','เลือกซอสราดอื่นได้','75'],['Ovaltine + Condensed Milk','โอวัลตินราดนมข้น','79'],['Almond Croffle','ครอฟเฟิลอัลมอนด์','90'],['Banana Croffle','ครอฟเฟิลกล้วย','90'],['Oreo Croffle','ครอฟเฟิลโอรีโอ้','90']]},
{title:'Topping',label:'ท็อปปิ้ง',group:'other',items:[['Frappe','ปั่น','+25'],['Oat Milk','นมโอ๊ต','+20'],['Add Shot','เพิ่มช็อต','+25'],['A glass of ice','น้ำแข็งเปล่า 1 แก้ว','+7']]}
];
const menuList=document.querySelector('#menu-list');
function renderMenu(filter='all'){const selected=filter==='all'?menuData:menuData.filter(category=>category.group===filter);menuList.innerHTML=selected.map(category=>`<article class="menu-category"><header class="menu-category-head"><h3>${category.title}</h3><span>${category.label}</span></header>${category.items.map(item=>`<div class="menu-item"><div><strong>${item[0]}</strong><small>${item[1]}</small></div><span class="menu-price">${item[2]}</span></div>`).join('')}</article>`).join('')}
document.querySelectorAll('.menu-filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.menu-filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderMenu(button.dataset.filter)}));renderMenu();
const header=document.querySelector('#site-header');const toggle=document.querySelector('#menu-toggle');const nav=document.querySelector('#site-nav');
window.addEventListener('scroll',()=>header.classList.toggle('fixed',scrollY>80),{passive:true});
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'ปิดเมนู':'เปิดเมนู')});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const items=document.querySelectorAll('.reveal');if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver'in window)){items.forEach(el=>el.classList.add('visible'))}else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});items.forEach(el=>observer.observe(el))}
document.querySelector('#year').textContent=new Date().getFullYear();
const menuDialog=document.querySelector('#menu-dialog');const menuDialogImage=document.querySelector('#menu-dialog-image');const menuDialogCaption=document.querySelector('#menu-dialog-caption');let menuDialogTrigger=null;
document.querySelectorAll('.menu-board-open').forEach(button=>button.addEventListener('click',()=>{if(typeof menuDialog.showModal!=='function'){window.open(button.dataset.dialogSrc,'_blank','noopener');return}menuDialogTrigger=button;menuDialogImage.src=button.dataset.dialogSrc;menuDialogImage.alt=button.dataset.dialogAlt;menuDialogCaption.textContent=button.dataset.dialogCaption;menuDialog.showModal()}));
menuDialog.addEventListener('click',event=>{if(event.target===menuDialog)menuDialog.close()});menuDialog.addEventListener('close',()=>{menuDialogImage.removeAttribute('src');if(menuDialogTrigger)menuDialogTrigger.focus()});
